export const routeNames = {
  general: {
    landing: "/",
    login: "/login",
    addCategory: "/add-category",
    addSubCategory: "/add-sub-category",
    viewSubCategories: "/view-sub-category",
    viewCategory: "/view-categories",
    addProduct: "/add-product",
    viewProducts: "/view-products",
    addExpenses: "/add-expenses",
    viewExpesnes: "/view-expenses",
    addSale: "/add-sale",
    viewSales: "/view-sales",
    revenue: "/view-revenue",
    addRevenue: "/add-revenue",
    orders: "/orders",
    settings: "/settings",
    aboutUs: "/about-us",
    users: "/users",
    addCoupen: "/add-coupen",
    viewCoupens: "/view-coupens",
  },
};
