export const routeNames = {
  general: {
    landing: "/",
    login: "/login",
    addCategory: "/add-category",
    addSubCategory: "/add-sub-category",
    viewSubCategories: "/view-sub-category",
    viewCategory: "/view-categories",
    addProduct: "/add-product",
    viewProducts: "/view-products",
    addExpenses: "/add-expenses",
    viewExpesnes: "/view-expenses",
    addSale: "/add-sale",
    viewSales: "/view-sales",
    revenue: "/view-revenue",
    addRevenue: "/add-revenue",
    orders: "/orders",
    addOrder: "/add-order",
    settings: "/settings",
    aboutUs: "/about-us",
    users: "/view-users",
    addUser: "/add-user",
    addCoupen: "/add-coupen",
    viewCoupens: "/view-coupens",
    addBlog: "/add-blog",
    viewBlog: "/view-blogs",
    addFaq: "/add-faq",
    viewFaq: "/view-faqs",
  },
};
